apiVersion: v1
kind: Service
metadata:
  name: k8sdemos-api-service
  labels:
    app: k8sdemo-api
spec:
  selector:
    app: k8sdemo-api
  ports:
    - protocol: TCP
      port: 4000 # Service port
      targetPort: 4000 # Container port
  type: NodePort # change to LoadBalancer if running in cloud
